package app;

import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ruivsan21
 */
public class MainFrame extends javax.swing.JFrame
{
    public static String username;
    public static String firstName;
    public static String lastName;
    public static ArrayList <JPanel> panels = new ArrayList<>();
    public static ArrayList <JPanel> mainPanels = new ArrayList<>();
    public static boolean mealPlanDone = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        
        LogIn li = new LogIn();
        CreateNewAccount cna = new CreateNewAccount();
        MainScreen ms = new MainScreen(username);
        AddNewDish and = new AddNewDish(ms);
        MealPlanDone mpd = new MealPlanDone();

        this.add(li);
        this.add(cna);
        this.add(ms);
        this.add(and);
        this.add(mpd);
        
        panels.add(li);
        panels.add(cna);
        panels.add(ms);
        panels.add(and);
        panels.add(mpd);
        
        Rectangle r = this.getContentPane().getBounds();
        
        for (int i = 0; i < panels.size(); i++)
        {
            panels.get(i).setSize(r.width, r.height);
            panels.get(i).setLocation(0, 0);
        }
        
        setPanelVisible(0);
        
        this.setLocation(400, 200);
    }
    

    public static void setPanelVisible(int pn)
    {
        for (int i = 0; i < panels.size(); i++)
        {
            panels.get(i).setVisible(false);
        }
        panels.get(pn).setVisible(true);
    }
    
    
    public static Connection setConnection(Connection con)
    {
        try

        {

            Class.forName("org.apache.derby.jdbc.ClientDriver");

        } catch (ClassNotFoundException e)

        {

            System.out.println("No JDBC Driver");

            e.printStackTrace();

        }

        try
        {

            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Users", "ad", "ad");

        } catch (Exception e)
        {

            System.out.println("error");

        }
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
